version: "3.9"

services:
  app:
    build: .
    container_name: app
    command: bin/rails server -b 0.0.0.0
    volumes:
      - .:/app
    ports:
      - "3005:3005"
    depends_on:
      - db
    environment:
      DATABASE_URL: "mysql2://root:password@db:3506/app_db"

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: app_db_development
    ports:
      - "3506:3506"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
